#!/usr/bin/env python

import sys
import json
import os.path
import socket

def main():
    range_file_name = "/var/cfengine/inputs/config_files_repo/range.json"
    if not os.path.isfile(range_file_name):
        sys.exit(1)
    hostname = socket.getfqdn()
   
    ver = sys.version_info[:2]
    version = ver[0] * 10 + ver[1]
     
    if version >= 26:
        with open(range_file_name, "r") as range_file_r:
            range_dict = json.load(range_file_r)
    else:
        range_file_r = open(range_file_name, "r")
        range_dict = json.load(range_file_r)
        range_file_r.close()

    for range in range_dict:
        if hostname in range_dict[range]:
            print "+{0}".format(range)

    # all are under generic_host
    print "+generic_host"

if __name__ == '__main__':
    main()
            
