#!/bin/bash

## This module is used to read /etc/roles_classes
## file and print them to raise CFEngine class

export=$PATH:/bin
roles_file="/etc/roles_classes"

# if the roles file does not exist yet, or is empty,
# raise generic_hosts class, 
# so CFE can configure the most basic stuffs

if [[ ! -s "${roles_file}" ]]
then
    echo "+generic_host"

else
    cat "${roles_file}"
fi
